In [5]:
import numpy as np

array([1, 2, 3])

In [6]:
np.zeros([2,4], dtype=float)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [8]:
np.ones([2,4], dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [9]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [11]:
np.full([3,5], 6.9)

array([[6.9, 6.9, 6.9, 6.9, 6.9],
       [6.9, 6.9, 6.9, 6.9, 6.9],
       [6.9, 6.9, 6.9, 6.9, 6.9]])

In [ ]:
np.random.random((4,4),)

TypeError: random() got an unexpected keyword argument 'dtype'

In [ ]:
np.random.normal(0,1)

array indexing & slicing1

In [ ]:
x1= np.random.randint(20, size=6)

array([ 9, 11, 18,  4,  1,  3], dtype=int32)